include: package:flutter_lints/flutter.yaml

# Custom rules and settings.
analyzer:
    exclude:
        - build/** # Excludes generated build files from analysis.

# Lints for code style
linter:
    rules:
        always_declare_return_types: true
        always_put_control_body_on_new_line: true
        always_put_required_named_parameters_first: true
        annotate_overrides: true
        avoid_annotating_with_dynamic: true
        avoid_empty_else: true
        avoid_init_to_null: true
        avoid_print: true
        avoid_return_types_on_setters: true
        avoid_single_cascade_in_expression_statements: true
        avoid_types_as_parameter_names: true
        await_only_futures: true

        # Lints for effective Dart
        camel_case_types: true
        cancel_subscriptions: true
        close_sinks: true
        control_flow_in_finally: true
        empty_catches: false
        hash_and_equals: true
        iterable_contains_unrelated_type: true
        list_remove_unrelated_type: true
        non_constant_identifier_names: false
        null_closures: true
        omit_local_variable_types: false
        prefer_collection_literals: true
        prefer_conditional_assignment: true
        prefer_const_constructors: true
        prefer_const_declarations: true
        prefer_const_literals_to_create_immutables: true
        prefer_final_fields: true
        prefer_final_locals: true
        prefer_for_elements_to_map_fromIterable: true
        prefer_function_declarations_over_variables: true
        prefer_generic_function_type_aliases: true
        prefer_if_elements_to_conditional_expressions: true
        prefer_is_empty: true
        prefer_is_not_empty: true
        prefer_iterable_whereType: true
        prefer_null_aware_operators: true
        prefer_relative_imports: true
        prefer_single_quotes: true
        prefer_spread_collections: true
        recursive_getters: true
        sort_child_properties_last: true
        test_types_in_equals: true
        throw_in_finally: true
        unawaited_futures: true
        unnecessary_brace_in_string_interps: true
        unnecessary_const: true
        unnecessary_lambdas: true
        unnecessary_new: true
        unnecessary_null_in_if_null_operators: true
        unnecessary_overrides: true
        unnecessary_this: true
        use_full_hex_values_for_flutter_colors: true
        use_key_in_widget_constructors: true
        use_rethrow_when_possible: true

# Additional configurations for specific project needs
strong-mode:
    implicit-casts: false
    implicit-dynamic: false
